# Generated by Django 2.2.7 on 2020-12-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201222_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.TextField(default='2020-12-22 20:29:28', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TextField(default='2020-12-22 20:29:28', null=True),
        ),
    ]
