# Generated by Django 2.2.7 on 2020-12-22 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_auto_20201222_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='partner',
        ),
        migrations.AddField(
            model_name='chat',
            name='partner',
            field=models.ManyToManyField(related_name='partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.TextField(default='2020-12-22 22:51:53', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TextField(default='2020-12-22 22:51:53', null=True),
        ),
    ]
